### ISSUE TITLE
fix vulnerabilities in xelJS

### ISSUE THREAD

**Issue by any1one** [xel-software/xel-developers-tools#5]
the mocha dependency contains vulnerabilities that needs to be fixed.
run `npm audit` for more informations

**Comment by tieandsuit** [comment]
'xeljs' is not in the npm registry.
i forgot to publish it . in to do list

**Comment by any1one** [comment]
regardless, those vulnerabilities need to be fixed before, one of them if classified as critical

**Comment by tieandsuit** [comment]
Requesting of xelja folder removal until its bug free. Need more time and don't want that buged item in official github. I have a fork of it and as soon it's fixed I will submit it again.
